import { AxiosError } from "axios";

export function handleAxiosError(err: AxiosError) {
  //You can Handle the error here
}
